// Shared seed data for the CareerCluster reference collection that drives the
// parent portal's Career Insights. Used by both the full db:seed (wipes
// everything) and db:seed-careers (safe to run against a live database).
export const careerClustersData = [
  { clusterId: "stem-engineering", order: 1, title: "Engineering & Technology", emoji: "⚙️", minScore: 65, color: "border-blue-500 bg-blue-50", description: "Design, build and solve real-world problems through mathematics and physical sciences.", subjects: ["Mathematics", "Physics", "Science"], careers: ["Mechanical Engineer", "Civil Engineer", "Electrical Engineer", "Software Engineer", "Aerospace Engineer", "Robotics Engineer"] },
  { clusterId: "computing", order: 2, title: "Computing & Data Science", emoji: "💻", minScore: 65, color: "border-indigo-500 bg-indigo-50", description: "Build software, analyse data and shape the digital world.", subjects: ["Mathematics", "Physics", "Computer Science"], careers: ["Software Developer", "Data Scientist", "Cybersecurity Analyst", "AI/ML Engineer", "Cloud Architect", "UX Designer"] },
  { clusterId: "medicine", order: 3, title: "Medicine & Health Sciences", emoji: "🩺", minScore: 70, color: "border-green-500 bg-green-50", description: "Understand the human body and help people live healthier lives.", subjects: ["Biology", "Chemistry", "Science", "Mathematics"], careers: ["Medical Doctor", "Pharmacist", "Nurse", "Biochemist", "Physiotherapist", "Dentist"] },
  { clusterId: "law-social", order: 4, title: "Law & Social Sciences", emoji: "⚖️", minScore: 65, color: "border-purple-500 bg-purple-50", description: "Understand society, argue cases and shape policy.", subjects: ["History", "English", "Literature", "Geography"], careers: ["Lawyer", "Judge", "Political Scientist", "Sociologist", "Human Rights Officer", "Diplomat"] },
  { clusterId: "business", order: 5, title: "Business & Finance", emoji: "📈", minScore: 60, color: "border-yellow-500 bg-yellow-50", description: "Drive economic growth through entrepreneurship, finance and management.", subjects: ["Mathematics", "Economics", "Business Studies", "History"], careers: ["Accountant", "Financial Analyst", "Entrepreneur", "Actuary", "Investment Banker", "Business Consultant"] },
  { clusterId: "arts-communication", order: 6, title: "Arts, Media & Communication", emoji: "🎨", minScore: 60, color: "border-rose-500 bg-rose-50", description: "Tell stories, create content and connect people through language and creativity.", subjects: ["English", "Literature", "History", "Art"], careers: ["Journalist", "Author", "Graphic Designer", "Film Director", "Marketing Manager", "Public Relations Specialist"] },
  { clusterId: "environment", order: 7, title: "Environment & Earth Sciences", emoji: "🌍", minScore: 60, color: "border-teal-500 bg-teal-50", description: "Protect the planet and understand natural systems.", subjects: ["Geography", "Biology", "Chemistry", "Science"], careers: ["Environmental Scientist", "Geologist", "Urban Planner", "Climate Researcher", "Marine Biologist", "Conservationist"] },
  { clusterId: "education", order: 8, title: "Education & Psychology", emoji: "📚", minScore: 55, color: "border-orange-500 bg-orange-50", description: "Shape minds, support development and understand human behaviour.", subjects: ["English", "Biology", "History", "Literature"], careers: ["Teacher", "School Counsellor", "Psychologist", "Educational Researcher", "Child Development Specialist", "Social Worker"] },
]
